services:
  bukkit:
    stdin_open: true
    restart: always
    tty: true
    env_file:
      - env.list
    volumes:
      - './data:/data'
    ports:
      - '25565:25565'
    image: cmunroe/bukkit
    container_name: hcraft
